// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
///
/// await Firebase.initializeApp(
///
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCXZ903Fcdl72VZVMuIGrn_0QOS9sWY7rQ',
    appId: '1:987179287539:web:c4d24510bb982f49c0c886',
    messagingSenderId: '987179287539',
    projectId: 'online-clearance-5d891',
    authDomain: 'online-clearance-5d891.firebaseapp.com',
    storageBucket: 'online-clearance-5d891.firebasestorage.app',
    measurementId: 'G-4Y0BYX1ZQ9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD4gAy2hZjU0QgvszXWijDv2x7wjhUvYpY',
    appId: '1:987179287539:android:a543422f5fadda3ec0c886',
    messagingSenderId: '987179287539',
    projectId: 'online-clearance-5d891',
    storageBucket: 'online-clearance-5d891.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAdggne74YtqHeULN1x-XZ2hchg1yoLPJQ',
    appId: '1:987179287539:ios:d89c865fa3991187c0c886',
    messagingSenderId: '987179287539',
    projectId: 'online-clearance-5d891',
    storageBucket: 'online-clearance-5d891.firebasestorage.app',
    iosBundleId: 'com.example.onlineClearance',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAdggne74YtqHeULN1x-XZ2hchg1yoLPJQ',
    appId: '1:987179287539:ios:d89c865fa3991187c0c886',
    messagingSenderId: '987179287539',
    projectId: 'online-clearance-5d891',
    storageBucket: 'online-clearance-5d891.firebasestorage.app',
    iosBundleId: 'com.example.onlineClearance',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCXZ903Fcdl72VZVMuIGrn_0QOS9sWY7rQ',
    appId: '1:987179287539:web:44f224de186c9b6bc0c886',
    messagingSenderId: '987179287539',
    projectId: 'online-clearance-5d891',
    authDomain: 'online-clearance-5d891.firebaseapp.com',
    storageBucket: 'online-clearance-5d891.firebasestorage.app',
    measurementId: 'G-KBRQPZS4S3',
  );
}
